/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
  * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/

#ifndef ROOCFAUTO001PDF
#define ROOCFAUTO001PDF

#include "RooAbsPdf.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"
 
class RooCFAuto001Pdf : public RooAbsPdf {
public:
  RooCFAuto001Pdf() {} ; 
  RooCFAuto001Pdf(const char *name, const char *title,
	      RooAbsReal& _tprime_mass_sum_pdf,
	      RooAbsReal& _mass);
  RooCFAuto001Pdf(const RooCFAuto001Pdf& other, const char* name=0) ;
  virtual TObject* clone(const char* newname) const { return new RooCFAuto001Pdf(*this,newname); }
  inline virtual ~RooCFAuto001Pdf() { }

protected:

  RooRealProxy tprime_mass_sum_pdf ;
  RooRealProxy mass ;
  
  Double_t evaluate() const ;

private:

  ClassDef(RooCFAuto001Pdf,1) // Your description goes here...
};
 
#endif
